name: bloc_counter
description: A counter app built in Flutter with BLoC.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test: ^0.8.1
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1


flutter:
  uses-material-design: true

        
    
    
                                      